const PDFDocument = require("pdfkit");

function generateMeetingPDF(res, meeting){

  const doc = new PDFDocument({ margin: 50 });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename=${meeting.title.replace(/\s+/g,"_")}.pdf`
  );

  doc.pipe(res);

  /* ---------- HEADER ---------- */

  doc
    .fontSize(24)
    .fillColor("#4F46E5")
    .text("Meeting Minutes", { align: "center" });

  doc.moveDown();

  /* ---------- MEETING DETAILS ---------- */

  doc
    .fillColor("#000000")
    .fontSize(14)
    .text(`Title: ${meeting.title}`);

  doc.text(`Client / Project: ${meeting.client || "-"}`);

  doc.text(`Date: ${new Date(meeting.date).toDateString()}`);

  doc.moveDown();

  /* ---------- PARTICIPANTS ---------- */

  if(meeting.participants && meeting.participants.length){

    doc
      .fontSize(16)
      .text("Participants");

    doc.moveDown(0.5);

    meeting.participants.forEach(p => {
      doc
        .fontSize(12)
        .text(`• ${p.username} (${p.email})`);
    });

    doc.moveDown();

  }

  /* ---------- TASK TABLE ---------- */

  doc
    .fontSize(16)
    .text("Discussion Points");

  doc.moveDown();

  const tableTop = doc.y;

  const col1 = 50;
  const col2 = 90;
  const col3 = 240;
  const col4 = 360;
  const col5 = 470;

  /* Header background */

  doc
    .rect(col1, tableTop, 500, 20)
    .fill("#4F46E5");

  doc
    .fillColor("#ffffff")
    .fontSize(11)
    .text("Sr", col1 + 5, tableTop + 5)
    .text("Topic", col2 + 5, tableTop + 5)
    .text("Action", col3 + 5, tableTop + 5)
    .text("Responsible", col4 + 5, tableTop + 5)
    .text("Deadline", col5 + 5, tableTop + 5);

  let y = tableTop + 25;

  meeting.tasks.forEach((task,index)=>{

    const deadline = task.deadline
      ? new Date(task.deadline).toDateString()
      : "-";

    doc
      .fillColor("#000000")
      .fontSize(10)
      .text(index + 1, col1 + 5, y)
      .text(task.title || "-", col2 + 5, y, { width: 130 })
      .text(task.action || "-", col3 + 5, y, { width: 110 })
      .text(task.assignedTo?.username || "-", col4 + 5, y)
      .text(deadline, col5 + 5, y);

    y += 25;

  });

  doc.moveDown(3);

  /* ---------- FOOTER ---------- */

  doc
    .fontSize(10)
    .fillColor("#6B7280")
    .text(
      "Generated by Smart MoM System",
      50,
      doc.page.height - 50,
      { align: "center" }
    );

  doc.end();
}

module.exports = generateMeetingPDF;